stages:
  # - test
  - build
  - deploy

# Run test on develop:
#   stage: test
#   only:
#     - develop
#   script:
#     - docker build -t crmjaen-angular-test:$CI_PIPELINE_ID -f docker/DockerfileTests .

Build on develop:
  stage: build
  only:
    - develop
  script:
    - docker build -t crmjaen-angular:$CI_PIPELINE_ID -f docker/Dockerfile .
    - docker tag crmjaen-angular:$CI_PIPELINE_ID $SERVER_IP:5000/crmjaen-angular
    - docker push $SERVER_IP:5000/crmjaen-angular

Deploy to develop:
  stage: deploy
  only:
    - develop
  script:
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $SERVER_IP:5000/crmjaen-angular"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f crmjaen_angular || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d --network='nginx_default' --name crmjaen_angular $SERVER_IP:5000/crmjaen-angular"
